[workspace]
members = [
    "omkit",
    "omkit-vcf",
]
resolver = "3"

[workspace.package]
license = "MIT OR Apache-2.0"
edition = "2024"
authors = ["The omkit project developers"]
description = "A cross-platform command line toolkit for omics-based analysis"
homepage = "https://github.com/stjude-rust-labs/omkit"
repository = "https://github.com/stjude-rust-labs/omkit"
rust-version = "1.94.0"

[workspace.dependencies]
anyhow = "1.0.102"
chainfile = "0.3.0"
clap = { version = "4.6.0", features = ["derive"] }
noodles = { version = "0.108.0", features = ["bgzf", "fasta", "vcf"] }
omics = { version = "0.2.0", features = ["coordinate"] }
omkit-vcf = { path = "omkit-vcf" }
thiserror = "2.0.18"

[workspace.lints.rust]
missing_docs = "warn"

[workspace.lints.rustdoc]
broken_intra_doc_links = "warn"
